spring:
  application:
    name: executionpilot
  data:
    mongodb:
      uri: ${MONGODB_EXECPILOT_URI}
      auto-index-creation: true

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
