package com.executionpilot.workflow.validator;

public enum ValidationErrorCode {
    MISSING_START_STATE,
    MULTIPLE_START_STATES,
    START_STATE_TYPE_MISMATCH,
    MISSING_END_STATE,
    MULTIPLE_END_STATES,
    END_STATE_TYPE_MISMATCH,
    INVALID_TRANSITION_SOURCE,
    INVALID_TRANSITION_TARGET,
    DUPLICATE_TRANSITION,
    SELF_LOOP_DETECTED,
    CYCLE_DETECTED,
    UNREACHABLE_STATES,
    TOPOLOGICAL_SORT_FAILED
}
